# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:17
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
