# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170504_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
    ]
