# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170504_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(blank=True, max_length=254, verbose_name='Email address'),
        ),
    ]
