# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 13:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('daily_rate', models.PositiveSmallIntegerField()),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UnauthorisedItemRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('C', 'Confirmed'), ('P', 'In process'), ('F', 'Completed'), ('E', 'Canceled')], default='N', max_length=1)),
                ('rental_date_start', models.DateField()),
                ('rental_date_out', models.DateField()),
                ('rental_date_returned', models.DateTimeField(blank=True, null=True)),
                ('rental_amount_due', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
        ),
        migrations.CreateModel(
            name='UserItemRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('C', 'Confirmed'), ('P', 'In process'), ('F', 'Completed'), ('E', 'Canceled')], default='N', max_length=1)),
                ('rental_date_start', models.DateField()),
                ('rental_date_out', models.DateField()),
                ('rental_date_returned', models.DateTimeField(blank=True, null=True)),
                ('rental_amount_due', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
