# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unauthoriseditemrental',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='useritemrental',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='unauthoriseditemrental',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Confirmed'), ('P', 'In process'), ('+', 'Completed'), ('-', 'Canceled')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='useritemrental',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Confirmed'), ('P', 'In process'), ('F', 'Completed')], default='N', max_length=1),
        ),
    ]
