# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170504_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=400, unique=True),
        ),
    ]
