# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:13
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170515_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthoriseditemrental',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
