# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170523_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemrental',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Confirmed'), ('P', 'In process'), ('F', 'Completed'), ('-', 'Canceled')], default='N', max_length=1),
        ),
    ]
